const IPC_MESSAGES = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  GET_TOKEN: 'GET_TOKEN',
  CREATE_VIEW: 'CREATE_VIEW',
  REMOVE_VIEW: 'REMOVE_VIEW',
  EXTERNAL_LINK: 'EXTERNAL_LINK',
  RELOAD: 'RELOAD'
}

module.exports = {
  IPC_MESSAGES
}
